### ISSUE TITLE
some of the mouths are see through.

### ISSUE THREAD

**Issue by cool23819** [sh0wer1ee/DLPortraits#5]
I've noticed that a few of the portraits' mouths are see-through such as Belladonna. she is one I know of as of now.

**Comment by sh0wer1ee** [comment]
I have tested all the mouth parts of Bella's, but didn't catch the situation as you said.
Maybe it happened when some sprites failed loading? If so re-clicking the sprite will solve the problem.
It would be helpful if you can upload some screenshots of this issue.

**Comment by cool23819** [comment]
Perhaps it was just that the inside of the mouth when it's open was white, I just didn't realize that back in her event. My apologies (both for this and the late response)

**Comment by sh0wer1ee** [comment]
No problem, and thanks for your reply.
