### ISSUE TITLE
so this isn't exactly an issue with the viewer itself but...

### ISSUE THREAD

**Issue by cool23819** [sh0wer1ee/DLPortraits#6]
both the lizard and lizardless regular Faris have the same title which I think might be causing issues with the dialogue generator, so could you probably label them (normal 1) and (normal 2) if at all possible? if not, sorry for bothering you.

**Comment by sh0wer1ee** [comment]
Fixed. [`9c5e40c`](https://github.com/sh0wer1ee/DLPortraits/commit/9c5e40cd8fbdadbf61eb287c913ef7e353dfa273)
And I also fixed other conflicted items.
